unit10Task2Commit
myFreeOrgan/playwright_tests_with_po pull request #2
Opened 2024-07-04 08:40 UTC by DenysStetsenko54321

2024-07-04 12:55 UTC, AlinaZhykharieva requested changes

2024-07-04 12:55 UTC, AlinaZhykharieva commented on src/pages/Inventory.page.js
> +        return { name, price, description };
I did not get the purpose of this method. this code is the same as we have in the previous method

2024-07-04 12:55 UTC, AlinaZhykharieva commented on src/tests/addingRandomItemsToCard.spec.js
> +        const shoppingCartPage = new ShopingCartPage(page);
why we are not doing it in the fixtures?

2024-07-04 12:55 UTC, AlinaZhykharieva commented on src/pages/Inventory.page.js
> +        const count = Math.floor(Math.random() * itemCount) + 1;
maybe it would be better randomAmount?

2024-07-04 12:57 UTC, AlinaZhykharieva commented on src/pages/Inventory.page.js
> +    generateRandomIndexes(maxIndex, count) {
and this method should be moved to utils. it is not related directly to the page

2024-07-06 16:47 UTC, hlazkov commented on src/tests/addingRandomItemsToCard.spec.js
> +            expect(match).toBeDefined();
Could you please recheck on matchers, if there is any applicible? It should look like `toContain` or something similar.

2024-07-06 16:48 UTC, hlazkov commented on src/tests/addingRandomItemsToCard.spec.js
> +        expect(listOfItems.length).toBe(6);
This test will fail one day :) Do we really need to assert this?

2024-07-06 16:49 UTC, hlazkov requested changes
Looks nice! But please update the test itself!

2024-07-09 07:35 UTC, AlinaZhykharieva approved these changes

2024-07-09 08:10 UTC, merged